// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line basepage.qtpl:3
package views

//line basepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line basepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line basepage.qtpl:4
type Page interface {
//line basepage.qtpl:4
	Title() string
//line basepage.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line basepage.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line basepage.qtpl:4
	Body() string
//line basepage.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line basepage.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line basepage.qtpl:4
}

// Page prints a page implementing Page interface.

//line basepage.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line basepage.qtpl:12
	qw422016.N().S(`
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>`)
//line basepage.qtpl:17
	p.StreamTitle(qw422016)
//line basepage.qtpl:17
	qw422016.N().S(`</title>

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo right">Musiclib</a>
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <li><a href="/draft">Draft albums</a></li>
                    <li><a href="/sync">Sync</a></li>
                </ul>
            </div>
        </nav>

        `)
//line basepage.qtpl:37
	p.StreamBody(qw422016)
//line basepage.qtpl:37
	qw422016.N().S(`
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('select');
                var instances = M.FormSelect.init(elems, {});
            });

            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.materialboxed');
                var instances = M.Materialbox.init(elems, {});
            });
        </script>
    </body>
</html>
`)
//line basepage.qtpl:51
}

//line basepage.qtpl:51
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line basepage.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basepage.qtpl:51
	StreamPageTemplate(qw422016, p)
//line basepage.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line basepage.qtpl:51
}

//line basepage.qtpl:51
func PageTemplate(p Page) string {
//line basepage.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line basepage.qtpl:51
	WritePageTemplate(qb422016, p)
//line basepage.qtpl:51
	qs422016 := string(qb422016.B)
//line basepage.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line basepage.qtpl:51
	return qs422016
//line basepage.qtpl:51
}
