// Code generated by qtc from "draft-album-list.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Table page template. Implements BasePage methods.
//

//line draft-album-list.qtpl:3
package views

//line draft-album-list.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line draft-album-list.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line draft-album-list.qtpl:4
type DraftAlbumsRow interface {
	URL() string
	Path() string
	Artist() string
	Title() string
}

type DraftAlbumsPage struct {
	Rows []DraftAlbumsRow
}

//line draft-album-list.qtpl:17
func (p *DraftAlbumsPage) StreamTitle(qw422016 *qt422016.Writer) {
//line draft-album-list.qtpl:17
	qw422016.N().S(`
    Draft albums
`)
//line draft-album-list.qtpl:19
}

//line draft-album-list.qtpl:19
func (p *DraftAlbumsPage) WriteTitle(qq422016 qtio422016.Writer) {
//line draft-album-list.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-list.qtpl:19
	p.StreamTitle(qw422016)
//line draft-album-list.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line draft-album-list.qtpl:19
}

//line draft-album-list.qtpl:19
func (p *DraftAlbumsPage) Title() string {
//line draft-album-list.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-list.qtpl:19
	p.WriteTitle(qb422016)
//line draft-album-list.qtpl:19
	qs422016 := string(qb422016.B)
//line draft-album-list.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-list.qtpl:19
	return qs422016
//line draft-album-list.qtpl:19
}

//line draft-album-list.qtpl:22
func (p *DraftAlbumsPage) StreamBody(qw422016 *qt422016.Writer) {
//line draft-album-list.qtpl:22
	qw422016.N().S(`
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>Path</th>
                    <th>Artist</th>
                    <th>Title</th>
                </tr>
            </thead>

            <tbody>
`)
//line draft-album-list.qtpl:34
	for _, r := range p.Rows {
//line draft-album-list.qtpl:34
		qw422016.N().S(`                <tr>
                    <th><a href="`)
//line draft-album-list.qtpl:36
		qw422016.E().S(r.URL())
//line draft-album-list.qtpl:36
		qw422016.N().S(`">`)
//line draft-album-list.qtpl:36
		qw422016.E().S(r.Path())
//line draft-album-list.qtpl:36
		qw422016.N().S(`</a></th>
                    <td>`)
//line draft-album-list.qtpl:37
		qw422016.E().S(r.Artist())
//line draft-album-list.qtpl:37
		qw422016.N().S(`</td>
                    <td>`)
//line draft-album-list.qtpl:38
		qw422016.E().S(r.Title())
//line draft-album-list.qtpl:38
		qw422016.N().S(`</td>
                </tr>
`)
//line draft-album-list.qtpl:40
	}
//line draft-album-list.qtpl:40
	qw422016.N().S(`            </tbody>
        </table>
    </div>
`)
//line draft-album-list.qtpl:44
}

//line draft-album-list.qtpl:44
func (p *DraftAlbumsPage) WriteBody(qq422016 qtio422016.Writer) {
//line draft-album-list.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-list.qtpl:44
	p.StreamBody(qw422016)
//line draft-album-list.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line draft-album-list.qtpl:44
}

//line draft-album-list.qtpl:44
func (p *DraftAlbumsPage) Body() string {
//line draft-album-list.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-list.qtpl:44
	p.WriteBody(qb422016)
//line draft-album-list.qtpl:44
	qs422016 := string(qb422016.B)
//line draft-album-list.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-list.qtpl:44
	return qs422016
//line draft-album-list.qtpl:44
}
