// Code generated by qtc from "draft-album-details.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line draft-album-details.qtpl:1
package views

//line draft-album-details.qtpl:1
import "strconv"

//line draft-album-details.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line draft-album-details.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line draft-album-details.qtpl:4
type AlbumData interface {
	ID() string
	Path() string
	Artist() string
	Title() string
	Type() string
	DownloadSource() string
	Year() *int
	ReleaseYear() *int
}

type TrackData interface {
	ID() string
	Path() string
	TrackArtist() string
	Title() string
	Disc() int
	TrackNum() int
}

type DraftAlbumDetailsPage struct {
	AllDownloadSources []string
	AllAlbumTypes      []string

	Album  AlbumData
	Tracks []TrackData
}

type baseInputConfig struct {
	wraperClass string
	disabled    bool
	name        string
	label       string
}

type strInputConfig struct {
	baseInputConfig
	value string
}

type intInputConfig struct {
	baseInputConfig
	value *int
	min   *int
}

type selectConfig struct {
	baseInputConfig

	options  []string
	selected string
}

func takeIntPtr(val int) *int {
	return &val
}

//line draft-album-details.qtpl:63
func (p *DraftAlbumDetailsPage) StreamTitle(qw422016 *qt422016.Writer) {
//line draft-album-details.qtpl:63
	qw422016.N().S(`
    Draft albums
`)
//line draft-album-details.qtpl:65
}

//line draft-album-details.qtpl:65
func (p *DraftAlbumDetailsPage) WriteTitle(qq422016 qtio422016.Writer) {
//line draft-album-details.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-details.qtpl:65
	p.StreamTitle(qw422016)
//line draft-album-details.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line draft-album-details.qtpl:65
}

//line draft-album-details.qtpl:65
func (p *DraftAlbumDetailsPage) Title() string {
//line draft-album-details.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-details.qtpl:65
	p.WriteTitle(qb422016)
//line draft-album-details.qtpl:65
	qs422016 := string(qb422016.B)
//line draft-album-details.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-details.qtpl:65
	return qs422016
//line draft-album-details.qtpl:65
}

//line draft-album-details.qtpl:67
func (p *DraftAlbumDetailsPage) StreamBody(qw422016 *qt422016.Writer) {
//line draft-album-details.qtpl:67
	qw422016.N().S(`
    <form class="container" method="POST" enctype="multipart/form-data">
        <div class="card">
            <div class="row">
                <input type="hidden" name="album.id" value="`)
//line draft-album-details.qtpl:71
	qw422016.E().S(p.Album.ID())
//line draft-album-details.qtpl:71
	qw422016.N().S(`" />

                `)
//line draft-album-details.qtpl:74
	streammakeStrInput(qw422016, strInputConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			name:        "album.artist",
			label:       "Draft artist",
		},
		value: p.Album.Artist(),
	})
//line draft-album-details.qtpl:82
	qw422016.N().S(`

                `)
//line draft-album-details.qtpl:85
	streammakeStrInput(qw422016, strInputConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			name:        "album.title",
			label:       "Title",
		},
		value: p.Album.Title(),
	})
//line draft-album-details.qtpl:93
	qw422016.N().S(`

                `)
//line draft-album-details.qtpl:96
	streammakeStrInput(qw422016, strInputConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			disabled:    true,
			name:        "album.path",
			label:       "Path",
		},
		value: p.Album.Path(),
	})
//line draft-album-details.qtpl:105
	qw422016.N().S(`

                `)
//line draft-album-details.qtpl:108
	streammakeIntInput(qw422016, intInputConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			name:        "album.date",
			label:       "Year",
		},
		value: p.Album.Year(),
		min:   takeIntPtr(1990),
	})
//line draft-album-details.qtpl:117
	qw422016.N().S(`

                `)
//line draft-album-details.qtpl:120
	streammakeIntInput(qw422016, intInputConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			name:        "album.release_date",
			label:       "Release year",
		},
		value: p.Album.ReleaseYear(),
		min:   takeIntPtr(1990),
	})
//line draft-album-details.qtpl:129
	qw422016.N().S(`

                `)
//line draft-album-details.qtpl:132
	streammakeSelect(qw422016, selectConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			name:        "album.type",
			label:       "Type",
		},

		options:  p.AllAlbumTypes,
		selected: p.Album.Type(),
	})
//line draft-album-details.qtpl:142
	qw422016.N().S(`

                `)
//line draft-album-details.qtpl:145
	streammakeSelect(qw422016, selectConfig{
		baseInputConfig: baseInputConfig{
			wraperClass: "col s6",
			name:        "album.download_source",
			label:       "Download source",
		},

		options:  p.AllDownloadSources,
		selected: p.Album.DownloadSource(),
	})
//line draft-album-details.qtpl:155
	qw422016.N().S(`
            </div>
        </div>

        <table class="card">
            <!--thead>
                <tr>
                    <th>Path</th>
                    <th>Title</th>
                    <th></th>
                </tr>
            </thead-->

            <tbody>
                `)
//line draft-album-details.qtpl:169
	for i, t := range p.Tracks {
//line draft-album-details.qtpl:169
		qw422016.N().S(`
                <tr>
                    <th>
                        <input
                            type="hidden"
                            name="`)
//line draft-album-details.qtpl:174
		qw422016.E().S("tracks." + strconv.Itoa(i) + ".id")
//line draft-album-details.qtpl:174
		qw422016.N().S(`"
                            value="`)
//line draft-album-details.qtpl:175
		qw422016.E().S(t.ID())
//line draft-album-details.qtpl:175
		qw422016.N().S(`"
                        />

                        `)
//line draft-album-details.qtpl:179
		streammakeStrInput(qw422016, strInputConfig{
			baseInputConfig: baseInputConfig{
				name:     "tracks." + strconv.Itoa(i) + ".path",
				label:    "Path",
				disabled: true,
			},

			value: t.Path(),
		})
//line draft-album-details.qtpl:188
		qw422016.N().S(`
                    </th>
                    <td>
                        `)
//line draft-album-details.qtpl:192
		streammakeStrInput(qw422016, strInputConfig{
			baseInputConfig: baseInputConfig{
				name:  "tracks." + strconv.Itoa(i) + ".title",
				label: "Title",
			},

			value: t.Title(),
		})
//line draft-album-details.qtpl:200
		qw422016.N().S(`
                    </td>
                    <td>
                        `)
//line draft-album-details.qtpl:204
		streammakeIntInput(qw422016, intInputConfig{
			baseInputConfig: baseInputConfig{
				name:  "tracks." + strconv.Itoa(i) + ".track_num",
				label: "Track number",
			},

			min:   takeIntPtr(0),
			value: takeIntPtr(t.TrackNum()),
		})
//line draft-album-details.qtpl:213
		qw422016.N().S(`
                    </td>
                    <td>
                        `)
//line draft-album-details.qtpl:217
		streammakeIntInput(qw422016, intInputConfig{
			baseInputConfig: baseInputConfig{
				name:  "tracks." + strconv.Itoa(i) + ".disc",
				label: "Disc number",
			},

			min:   takeIntPtr(0),
			value: takeIntPtr(t.Disc()),
		})
//line draft-album-details.qtpl:226
		qw422016.N().S(`
                    </td>
                    <td>
                        `)
//line draft-album-details.qtpl:230
		streammakeStrInput(qw422016, strInputConfig{
			baseInputConfig: baseInputConfig{
				name:  "tracks." + strconv.Itoa(i) + ".track_artist",
				label: "TrackArtist",
			},

			value: t.TrackArtist(),
		})
//line draft-album-details.qtpl:238
		qw422016.N().S(`
                    </td>
                </tr>
                `)
//line draft-album-details.qtpl:241
	}
//line draft-album-details.qtpl:241
	qw422016.N().S(`
            </tbody>
        </table>

        <footer class="row right-align">
            <button class="btn waves-effect waves-light" type="submit">
                Save
                <i class="material-icons right"></i>
            </button>
        </footer>
    </form>
`)
//line draft-album-details.qtpl:252
}

//line draft-album-details.qtpl:252
func (p *DraftAlbumDetailsPage) WriteBody(qq422016 qtio422016.Writer) {
//line draft-album-details.qtpl:252
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-details.qtpl:252
	p.StreamBody(qw422016)
//line draft-album-details.qtpl:252
	qt422016.ReleaseWriter(qw422016)
//line draft-album-details.qtpl:252
}

//line draft-album-details.qtpl:252
func (p *DraftAlbumDetailsPage) Body() string {
//line draft-album-details.qtpl:252
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-details.qtpl:252
	p.WriteBody(qb422016)
//line draft-album-details.qtpl:252
	qs422016 := string(qb422016.B)
//line draft-album-details.qtpl:252
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-details.qtpl:252
	return qs422016
//line draft-album-details.qtpl:252
}

//line draft-album-details.qtpl:254
func streammakeIntInput(qw422016 *qt422016.Writer, c intInputConfig) {
//line draft-album-details.qtpl:254
	qw422016.N().S(`
<div class="input-field `)
//line draft-album-details.qtpl:255
	qw422016.E().S(c.wraperClass)
//line draft-album-details.qtpl:255
	qw422016.N().S(`">
    <input
        id="`)
//line draft-album-details.qtpl:257
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:257
	qw422016.N().S(`"
        `)
//line draft-album-details.qtpl:258
	if c.disabled {
//line draft-album-details.qtpl:258
		qw422016.N().S(`
            disabled
        `)
//line draft-album-details.qtpl:260
	}
//line draft-album-details.qtpl:260
	qw422016.N().S(`
        type="number"
        class="validate"
        name="`)
//line draft-album-details.qtpl:263
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:263
	qw422016.N().S(`"
        `)
//line draft-album-details.qtpl:264
	if c.value != nil {
//line draft-album-details.qtpl:264
		qw422016.N().S(`
            value="`)
//line draft-album-details.qtpl:265
		qw422016.N().D(*c.value)
//line draft-album-details.qtpl:265
		qw422016.N().S(`"
        `)
//line draft-album-details.qtpl:266
	}
//line draft-album-details.qtpl:266
	qw422016.N().S(`
        `)
//line draft-album-details.qtpl:267
	if c.min != nil {
//line draft-album-details.qtpl:267
		qw422016.N().S(`
            min="`)
//line draft-album-details.qtpl:268
		qw422016.N().D(*c.min)
//line draft-album-details.qtpl:268
		qw422016.N().S(`"
        `)
//line draft-album-details.qtpl:269
	}
//line draft-album-details.qtpl:269
	qw422016.N().S(`
    >
    <label for="`)
//line draft-album-details.qtpl:271
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:271
	qw422016.N().S(`">`)
//line draft-album-details.qtpl:271
	qw422016.E().S(c.label)
//line draft-album-details.qtpl:271
	qw422016.N().S(`</label>
</div>
`)
//line draft-album-details.qtpl:273
}

//line draft-album-details.qtpl:273
func writemakeIntInput(qq422016 qtio422016.Writer, c intInputConfig) {
//line draft-album-details.qtpl:273
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-details.qtpl:273
	streammakeIntInput(qw422016, c)
//line draft-album-details.qtpl:273
	qt422016.ReleaseWriter(qw422016)
//line draft-album-details.qtpl:273
}

//line draft-album-details.qtpl:273
func makeIntInput(c intInputConfig) string {
//line draft-album-details.qtpl:273
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-details.qtpl:273
	writemakeIntInput(qb422016, c)
//line draft-album-details.qtpl:273
	qs422016 := string(qb422016.B)
//line draft-album-details.qtpl:273
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-details.qtpl:273
	return qs422016
//line draft-album-details.qtpl:273
}

//line draft-album-details.qtpl:275
func streammakeStrInput(qw422016 *qt422016.Writer, c strInputConfig) {
//line draft-album-details.qtpl:275
	qw422016.N().S(`
<div class="input-field `)
//line draft-album-details.qtpl:276
	qw422016.E().S(c.wraperClass)
//line draft-album-details.qtpl:276
	qw422016.N().S(`">
    <input
        id="`)
//line draft-album-details.qtpl:278
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:278
	qw422016.N().S(`"
        `)
//line draft-album-details.qtpl:279
	if c.disabled {
//line draft-album-details.qtpl:279
		qw422016.N().S(`
            disabled
        `)
//line draft-album-details.qtpl:281
	}
//line draft-album-details.qtpl:281
	qw422016.N().S(`
        type="text"
        class="validate"
        name="`)
//line draft-album-details.qtpl:284
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:284
	qw422016.N().S(`"
        value="`)
//line draft-album-details.qtpl:285
	qw422016.E().S(c.value)
//line draft-album-details.qtpl:285
	qw422016.N().S(`"
    >
    <label for="`)
//line draft-album-details.qtpl:287
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:287
	qw422016.N().S(`">`)
//line draft-album-details.qtpl:287
	qw422016.E().S(c.label)
//line draft-album-details.qtpl:287
	qw422016.N().S(`</label>
</div>
`)
//line draft-album-details.qtpl:289
}

//line draft-album-details.qtpl:289
func writemakeStrInput(qq422016 qtio422016.Writer, c strInputConfig) {
//line draft-album-details.qtpl:289
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-details.qtpl:289
	streammakeStrInput(qw422016, c)
//line draft-album-details.qtpl:289
	qt422016.ReleaseWriter(qw422016)
//line draft-album-details.qtpl:289
}

//line draft-album-details.qtpl:289
func makeStrInput(c strInputConfig) string {
//line draft-album-details.qtpl:289
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-details.qtpl:289
	writemakeStrInput(qb422016, c)
//line draft-album-details.qtpl:289
	qs422016 := string(qb422016.B)
//line draft-album-details.qtpl:289
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-details.qtpl:289
	return qs422016
//line draft-album-details.qtpl:289
}

//line draft-album-details.qtpl:291
func streammakeSelect(qw422016 *qt422016.Writer, c selectConfig) {
//line draft-album-details.qtpl:291
	qw422016.N().S(`
<div class="input-field `)
//line draft-album-details.qtpl:292
	qw422016.E().S(c.wraperClass)
//line draft-album-details.qtpl:292
	qw422016.N().S(`">
    <select
        name="`)
//line draft-album-details.qtpl:294
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:294
	qw422016.N().S(`"
        id="`)
//line draft-album-details.qtpl:295
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:295
	qw422016.N().S(`"
    >
        `)
//line draft-album-details.qtpl:297
	for _, option := range c.options {
//line draft-album-details.qtpl:297
		qw422016.N().S(`
        <option
            `)
//line draft-album-details.qtpl:299
		if option == c.selected {
//line draft-album-details.qtpl:299
			qw422016.N().S(`
            selected
            `)
//line draft-album-details.qtpl:301
		}
//line draft-album-details.qtpl:301
		qw422016.N().S(`
            value="`)
//line draft-album-details.qtpl:302
		qw422016.E().S(option)
//line draft-album-details.qtpl:302
		qw422016.N().S(`"
            >`)
//line draft-album-details.qtpl:303
		qw422016.E().S(option)
//line draft-album-details.qtpl:303
		qw422016.N().S(`</option>
        `)
//line draft-album-details.qtpl:304
	}
//line draft-album-details.qtpl:304
	qw422016.N().S(`
    </select>
    <label for="`)
//line draft-album-details.qtpl:306
	qw422016.E().S(c.name)
//line draft-album-details.qtpl:306
	qw422016.N().S(`">`)
//line draft-album-details.qtpl:306
	qw422016.E().S(c.label)
//line draft-album-details.qtpl:306
	qw422016.N().S(`</label>
</div>
`)
//line draft-album-details.qtpl:308
}

//line draft-album-details.qtpl:308
func writemakeSelect(qq422016 qtio422016.Writer, c selectConfig) {
//line draft-album-details.qtpl:308
	qw422016 := qt422016.AcquireWriter(qq422016)
//line draft-album-details.qtpl:308
	streammakeSelect(qw422016, c)
//line draft-album-details.qtpl:308
	qt422016.ReleaseWriter(qw422016)
//line draft-album-details.qtpl:308
}

//line draft-album-details.qtpl:308
func makeSelect(c selectConfig) string {
//line draft-album-details.qtpl:308
	qb422016 := qt422016.AcquireByteBuffer()
//line draft-album-details.qtpl:308
	writemakeSelect(qb422016, c)
//line draft-album-details.qtpl:308
	qs422016 := string(qb422016.B)
//line draft-album-details.qtpl:308
	qt422016.ReleaseByteBuffer(qb422016)
//line draft-album-details.qtpl:308
	return qs422016
//line draft-album-details.qtpl:308
}
