// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line error.qtpl:1
package views

//line error.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line error.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line error.qtpl:2
type ErrorPage struct {
	Error error
}

//line error.qtpl:7
func (p *ErrorPage) StreamTitle(qw422016 *qt422016.Writer) {
//line error.qtpl:7
	qw422016.N().S(`Error`)
//line error.qtpl:7
}

//line error.qtpl:7
func (p *ErrorPage) WriteTitle(qq422016 qtio422016.Writer) {
//line error.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line error.qtpl:7
	p.StreamTitle(qw422016)
//line error.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line error.qtpl:7
}

//line error.qtpl:7
func (p *ErrorPage) Title() string {
//line error.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line error.qtpl:7
	p.WriteTitle(qb422016)
//line error.qtpl:7
	qs422016 := string(qb422016.B)
//line error.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line error.qtpl:7
	return qs422016
//line error.qtpl:7
}

//line error.qtpl:9
func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
//line error.qtpl:9
	qw422016.N().S(`
<div class="container">
    <div class="card-panel red white-text">
        `)
//line error.qtpl:12
	qw422016.E().S(p.Error.Error())
//line error.qtpl:12
	qw422016.N().S(`
    </div>
</div>
`)
//line error.qtpl:15
}

//line error.qtpl:15
func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
//line error.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line error.qtpl:15
	p.StreamBody(qw422016)
//line error.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line error.qtpl:15
}

//line error.qtpl:15
func (p *ErrorPage) Body() string {
//line error.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line error.qtpl:15
	p.WriteBody(qb422016)
//line error.qtpl:15
	qs422016 := string(qb422016.B)
//line error.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line error.qtpl:15
	return qs422016
//line error.qtpl:15
}
