version: '2'
services:
  postgres:
    restart: always
    image: postgres:11
    container_name: musiclib-postgres
    volumes:
      - ${PWD}/postgres.init.db/:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_DB: musicdb
    env_file:
      - ${PWD}/secrets/postgres/credentials.env
    ports:
      - "5433:5432"

  redis:
    restart: always
    image: redis:5
    container_name: musiclib-redis
    ports:
      - "6380:6379"
